### ISSUE TITLE
Better UI for status update cross-posting option

### ISSUE THREAD

**Issue by chrisaldrich** [L1am0/mastodon_wordpress_autopost#14]
Given that I suspect most use Mastodon for short status updates (under their 500 character limit), it would be nice if there were an option for posting the_content from WordPress’ main body editor along with the URL and/or any hashtags. This way people could post short updates from their blog as status updates/asides and have the full post (or an automatically shortened version if too long) sent over with a link back to the original.

Currently the posting of Title/Link/Hashtags or Title/Content/Link/Hashtags is better for cross-posting longer blog articles which tend to have titles whereas status updates often don’t have titles.

From a UI perspective, it would also optionally be nice to have some type of character counter for the primary text box to fit into Mastodon’s guidelines. I recall there having been a plugin that did just this which might be repurposed: <https://wordpress.org/plugins/character-count-for-post-content-excerpt/>

To be able to switch between the various modes Title/Link/Hashtags; Title/Content/Link/Hashtags; and potentially this new Body/Link/Hashtags it would be nice if the Mastodon Autopost meta box had the option to also select between them in addition to the “Post to Mastodon” checkbox.

(Originally published at: http://boffosocko.com/2018/03/11/better-ui-for-status-update-cross-posting-option/)

**Comment by L1am0** [comment]
Dear chris,

thanks for your in depth comment and idea!
Currently the hellexis and I join forces to work together on a new/reworked mastodon plugin.

We base our work on the mastodon share plugin. Because of that this plugin is currently only in bugfix/maintainance mode and will be deprecated in the end of April.

Please have a look on helixes plugin https://de.wordpress.org/plugins/wp-mastodon-share/ as that one is the one we will continue. It gives you a better possibility to configure the post.

Thanks,
L1am0
